pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Fahd-DevOps/Aws-Ansible-Jenkins.git'
            }
        }

        stage('Run Ansible Playbook') {
            steps {
                // Execute ansible playbook
                withCredentials([sshUserPrivateKey(credentialsId: 'ansible-ssh-key-id', keyFileVariable: 'SSH_KEY')]) {
                    sh '''
                        chmod 600 $SSH_KEY
                        ansible-playbook -i hosts.yaml webserver-config.yaml
                    '''
                }
            }
        }
    }

    post {
        success {
            // Notify success
            echo 'Ansible playbook executed successfully!'
        }
        failure {
            // Notify failure
            echo 'Ansible playbook execution failed!'
        }
    }
}