pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                sh 'echo "Checkout code from GitHub repository..."'
                git branch: 'main', url: 'https://github.com/Fahd-DevOps/Aws-Ansible-Jenkins'
            }
        }

        stage('Build Using Ansible') {
            steps {
                // Example build steps
                sh 'echo "Building the project..."'
                ansiblePlaybook credentialsId: 'ansible-ssh-key-id', disableHostKeyChecking: true, installation: 'ansible2', inventory: 'app/hosts.yaml', playbook: 'app/webserver-config.yaml', vaultTmpPath: ''
            }
        }
    }

    post {
        success {
            // Notification for successful build
            echo 'Build successful! Deploying...'
        }
        failure {
            // Notification for failed build
            echo 'Build failed!'
            // Add error handling or notification steps
        }
    }
}
